<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>NextTech.Api</RootNamespace>
    <UserSecretsId>2588aa30-80b1-44ca-b999-8401b11aa569</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NextTech.Application\NextTech.Application.csproj" />
    <ProjectReference Include="..\NextTech.Infrastructure\NextTech.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
</Project>
